
image: Visual Studio 2017
environment:
 nodejs_version: "9.4"
 my_gh_key:
  secure: 6JrDTNKaQ/maix74mVtuytKP4j84llskNk4YyTJcO54ncOXcIrGDVGo0twb9CkH3JdsoKQwD+s8XYMirAcbR1nyfJdBxI2eRuOiPh9F1sGY=
platform: x64
configuration: Release
install:
- ps: Install-Product node $env:nodejs_version $env:platform
- npm install -g node-gyp
build: off
build_script:
- echo %env_toto%
- echo %ghkey%
- echo %my_gh_key%
- node-gyp configure
- node-gyp build
- mkdir %APPVEYOR_BUILD_FOLDER%\bin
- copy %APPVEYOR_BUILD_FOLDER%\build\Release\test_addon_simple_hello.node %APPVEYOR_BUILD_FOLDER%\bin
- 7z a -ttar %APPVEYOR_BUILD_FOLDER%\build\Release\tmp.tar %APPVEYOR_BUILD_FOLDER%\bin
- 7z a -tgzip %APPVEYOR_BUILD_FOLDER%\build\Release\test_addon_simple_hello_win32.tar.gz %APPVEYOR_BUILD_FOLDER%\build\Release\tmp.tar
artifacts:
- path: build\Release\test_addon_simple_hello_win32.tar.gz
  name: test_addon_simple_hello_win32.tar.gz
deploy:
 provider: GitHub
 auth_token:
  secure: 6JrDTNKaQ/maix74mVtuytKP4j84llskNk4YyTJcO54ncOXcIrGDVGo0twb9CkH3JdsoKQwD+s8XYMirAcbR1nyfJdBxI2eRuOiPh9F1sGY=
 artifact: build\Release\test_addon_simple_hello_win32.tar.gz
 on:
  appveyor_repo_tag: false
