
language: node_js

node_js:
  - node

os:
  - linux
  - osx

before_install:
  - npm install -g node-gyp

script:
  - node-gyp configure
  - node-gyp build

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true